(function(){
'use strict';
const P=window.P;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}}
const S={cart:load('velora_cart',{}),favs:load('velora_favs',[]),cat:'Todo',q:'',sort:'featured',reservation:null,shared:null,visualItems:[],visualIndex:0,visualSource:'bag'};
const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(n);
const lines=()=>P.filter(p=>S.cart[p.id]).map(p=>({...p,qty:S.cart[p.id]}));
const count=()=>lines().reduce((a,x)=>a+x.qty,0); const total=()=>lines().reduce((a,x)=>a+x.qty*x.price,0);
function save(){try{localStorage.setItem('velora_cart',JSON.stringify(S.cart));localStorage.setItem('velora_favs',JSON.stringify(S.favs))}catch(e){}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1700)}
function encode(o){try{const b=new TextEncoder().encode(JSON.stringify(o));let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}catch(e){return''}}
function decode(v){try{let s=v.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=atob(s);return JSON.parse(new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0))))}catch(e){return null}}
function card(p){const fav=S.favs.includes(p.id);return `<article class="card"><button class="fav ${fav?'on':''}" data-fav="${p.id}">${fav?'♥':'♡'}</button><div class="art ${p.tone}" data-detail="${p.id}"><span>${p.symbol}</span><small class="badge">${p.badge}</small></div><div class="info" data-detail="${p.id}"><span class="cat">${p.cat}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="meta"><span>${p.color}</span><span>${p.meta}</span></div></div><div class="foot"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}">+ Agregar</button></div></article>`}
function renderChips(){const c=['Todo',...new Set(P.map(x=>x.cat))];$('#chips').innerHTML=c.map(x=>`<button data-cat="${x}" class="${S.cat===x?'on':''}">${x}</button>`).join('')}
function filtered(){let a=P.filter(p=>(S.cat==='Todo'||p.cat===S.cat)&&(!S.q||(`${p.name} ${p.cat} ${p.desc} ${p.feature} ${p.color}`).toLowerCase().includes(S.q.toLowerCase())));if(S.sort==='low')a.sort((a,b)=>a.price-b.price);if(S.sort==='high')a.sort((a,b)=>b.price-a.price);if(S.sort==='name')a.sort((a,b)=>a.name.localeCompare(b.name));return a}
function renderGrid(){const a=filtered();$('#grid').innerHTML=a.length?a.map(card).join(''):`<div class="empty" style="grid-column:1/-1"><h3>No encontré coincidencias</h3><p>Prueba otra búsqueda o vuelve a ver todo el catálogo.</p></div>`}
function counts(){const c=count();$('#bagCount').textContent=c;$('#dockCount').textContent=c||'';$('#bagTitleCount').textContent=c;$('#favCount').textContent=S.favs.length}
function add(id,n=1){S.cart[id]=Math.max(0,(S.cart[id]||0)+n);if(!S.cart[id])delete S.cart[id];S.reservation=null;save();counts();renderBag();toast('Agregado a tu bolsa')}
function qty(id,n){if(n<=0)delete S.cart[id];else S.cart[id]=n;S.reservation=null;save();counts();renderBag()}
function fav(id){S.favs=S.favs.includes(id)?S.favs.filter(x=>x!==id):[...S.favs,id];save();counts();renderGrid();toast(S.favs.includes(id)?'Guardado en favoritos':'Quitado de favoritos')}
function open(id){$('#overlay').classList.add('open');$('#'+id).classList.add('open')}
function close(id){$('#'+id).classList.remove('open');if(!$$('.drawer.open,.modal.open').length)$('#overlay').classList.remove('open')}
function closeAll(){$$('.drawer.open,.modal.open').forEach(x=>x.classList.remove('open'));$('#overlay').classList.remove('open')}
function renderBag(){const a=lines();if(!a.length){$('#bagBody').innerHTML=`<div class="empty"><div style="font-size:44px">🛍</div><h3>Tu bolsa está vacía</h3><p>Agrega productos y luego podrás verlos también en modo visual.</p><a href="#catalogo" class="btn primary" data-close="bagDrawer">Explorar</a></div>`;$('#bagFoot').innerHTML='';return}$('#bagBody').innerHTML=a.map(p=>`<div class="line"><div class="lineArt ${p.tone}">${p.symbol}</div><div class="lineInfo"><b>${p.name}</b><small>${p.color} · ${p.feature}</small><strong>${money(p.price)}</strong></div><div class="qty"><button data-qty="${p.id}" data-n="${p.qty-1}">${p.qty===1?'×':'−'}</button><span>${p.qty}</span><button data-qty="${p.id}" data-n="${p.qty+1}">+</button></div></div>`).join('');$('#bagFoot').innerHTML=`<div class="total"><span>Total referencial</span><b>${money(total())}</b></div><p>Pago únicamente al recoger. Disponibilidad y precio final se confirman en tienda.</p><div class="bagActions"><button id="bagVisualBtn" class="btn soft">◫ Ver compra</button><button id="bagShareQuick" class="btn soft">↗ Compartir</button><button id="prepare" class="btn primary big">▦ Preparar recojo</button></div>`}
function openBag(){renderBag();open('bagDrawer')}
function detail(id){const p=P.find(x=>x.id===id);if(!p)return;$('#detailBody').innerHTML=`<div class="detailArt ${p.tone}">${p.symbol}</div><span class="cat">${p.cat}</span><h2>${p.name}</h2><p>${p.desc}</p><div class="detailTags"><span>Color: ${p.color}</span><span>${p.feature}</span><span>${p.meta}</span><span>Recojo en tienda</span></div><div class="detailFoot"><b>${money(p.price)}</b><button class="btn primary" data-detailadd="${p.id}">Agregar a bolsa →</button></div>`;open('detailModal')}
function reservation(){const a=lines();if(!a.length)return;const code='VL-'+Date.now().toString(36).slice(-5).toUpperCase()+'-'+Math.random().toString(36).slice(2,5).toUpperCase();const d={code,created:new Date().toISOString(),items:a.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty,color:x.color,feature:x.feature,meta:x.meta,tone:x.tone,symbol:x.symbol,cat:x.cat}))};const base=location.href.split('#')[0];S.reservation={...d,link:base+'#bag='+encode(d)};close('bagDrawer');showReservation()}
function ensureReservation(){if(S.reservation)return S.reservation;const a=lines();if(!a.length)return null;const code='VL-DEMO-'+Math.random().toString(36).slice(2,5).toUpperCase();const d={code,created:new Date().toISOString(),items:a.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty,color:x.color,feature:x.feature,meta:x.meta,tone:x.tone,symbol:x.symbol,cat:x.cat}))};S.reservation={...d,link:location.href.split('#')[0]+'#bag='+encode(d)};return S.reservation}
function showReservation(){const r=S.reservation;if(!r)return;$('#codeBtn').innerHTML=`<span>CÓDIGO DE RECOJO</span><b>${r.code}</b>`;const q=$('#qr');q.innerHTML='';if(window.QRCode)new QRCode(q,{text:r.link,width:187,height:187,colorDark:'#09070d',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M});else q.innerHTML='<div style="font-size:10px;color:#111">QR disponible al cargar online.<br><br>'+r.code+'</div>';open('shareModal')}
async function copy(t,m='Copiado'){try{await navigator.clipboard.writeText(t);toast(m)}catch(e){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();toast(m)}}
async function share(){const r=ensureReservation();if(!r)return;if(navigator.share){try{await navigator.share({title:'Mi bolsa VELORA',text:'Bolsa '+r.code,url:r.link})}catch(e){}}else copy(r.link,'Link copiado')}
function itemsFromShared(items){return items.map(i=>{const p=P.find(x=>x.id===i.id)||{};return {...p,...i,tone:i.tone||p.tone||'purple',symbol:i.symbol||p.symbol||'◇',color:i.color||p.color||'Sin especificar',feature:i.feature||p.feature||'Selección guardada',meta:i.meta||p.meta||'',cat:i.cat||p.cat||'Producto'}})}
function openVisual(source='bag',items=null,code=null){let a;if(items)a=itemsFromShared(items);else a=lines();if(!a.length){toast('Tu bolsa está vacía');return}S.visualItems=a;S.visualIndex=0;S.visualSource=source;S.visualCode=code||(S.reservation&&S.reservation.code)||'BOLSA SIN CÓDIGO';renderVisual();close('bagDrawer');close('shareModal');close('sharedModal');open('visualModal')}
function renderVisual(){const a=S.visualItems,i=S.visualIndex,p=a[i];if(!p)return;const art=$('#visualArt');art.className='visualArt '+(p.tone||'purple');art.querySelector('.symbol').textContent=p.symbol||'◇';art.querySelector('.colorName').textContent=p.color||'Sin color';$('#visualCode').textContent=S.visualCode;$('#visualCounter').textContent=`${i+1} de ${a.length}`;$('#visualCat').textContent=p.cat||'Producto';$('#visualName').textContent=p.name;$('#visualPrice').textContent=money(p.price);$('#visualQty').textContent=`× ${p.qty||1}`;$('#visualColor').textContent=p.color||'Sin especificar';$('#visualFeature').textContent=p.feature||p.desc||'Selección guardada';$('#visualMeta').textContent=p.meta||'Presentación discreta';$('#visualThumbs').innerHTML=a.map((x,n)=>`<button class="thumb ${n===i?'on':''} ${x.tone||'purple'}" data-visual="${n}">${x.symbol||'◇'}</button>`).join('');$('#visualProgress').style.width=((i+1)/a.length*100)+'%';$('#visualPrev').style.opacity=a.length>1?'1':'.25';$('#visualNext').style.opacity=a.length>1?'1':'.25'}
function moveVisual(d){const n=S.visualItems.length;if(n<2)return;S.visualIndex=(S.visualIndex+d+n)%n;renderVisual()}
function visualToQr(){close('visualModal');if(S.reservation)showReservation();else{toast('Primero genera tu código de recojo');openBag()}}
function loadShared(){const m=location.hash.match(/^#bag=(.+)$/);if(!m)return;const o=decode(m[1]);if(!o||!Array.isArray(o.items))return;S.shared=o;$('#sharedTitle').textContent=o.code||'Selección VELORA';$('#sharedList').innerHTML=o.items.map(i=>`<div class="sharedLine"><span>${i.name} <small>×${i.qty}</small></span><b>${money(i.price*i.qty)}</b></div>`).join('');open('sharedModal')}
function useShared(){if(!S.shared)return;S.cart={};S.shared.items.forEach(i=>S.cart[i.id]=i.qty);save();counts();renderBag();close('sharedModal');history.replaceState(null,'',location.pathname+location.search);toast('Bolsa copiada a este equipo')}
function msg(by,t){const e=document.createElement('div');e.className='msg '+by;e.textContent=t;$('#rodMsgs').appendChild(e);$('#rodMsgs').scrollTop=$('#rodMsgs').scrollHeight}
function ask(t){t=(t||'').trim();if(!t)return;msg('u',t);let r='Puedo filtrar el catálogo, abrir tu bolsa, mostrar tu compra visual o explicarte el recojo.';const l=t.toLowerCase();if(l.includes('visual')||l.includes('imagen')){r=count()?'Te abro tu compra en modo visual. Puedes avanzar y retroceder entre productos.':'Primero agrega algo a tu bolsa y luego te la muestro en imágenes.';if(count())setTimeout(()=>openVisual('bag'),350)}else if(l.includes('bolsa')||l.includes('carrito')){r=count()?`Tienes ${count()} producto${count()>1?'s':''} por ${money(total())}. Te abro la bolsa.`:'Tu bolsa está vacía. Te llevo al catálogo.';setTimeout(()=>count()?openBag():location.hash='#catalogo',350)}else if(l.includes('pareja')){S.cat='Pareja';S.q='';renderChips();renderGrid();location.hash='#catalogo';r='Listo, te mostré opciones para pareja.'}else if(l.includes('discret')||l.includes('compact')){S.cat='Kits';S.q='';renderChips();renderGrid();location.hash='#catalogo';r='Te mostré kits y opciones compactas para una compra discreta.'}else if(l.includes('lubric')){S.cat='Lubricantes';S.q='';renderChips();renderGrid();location.hash='#catalogo';r='Te muestro lubricantes del catálogo.'}else if(l.includes('recojo')||l.includes('qr')){r=count()?'Abre la bolsa y toca “Preparar recojo”. Después podrás ver QR, código y tu compra visual.':'Agrega productos primero y luego podrás generar el QR.'}setTimeout(()=>msg('r',r),240)}
function rodOpen(seed){$('#rod').classList.add('open');if(seed)setTimeout(()=>ask(seed),100)}
function voice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('La voz no está habilitada en este navegador');return}const r=new R();r.lang='es-PE';r.onresult=e=>ask(e.results[0][0].transcript);r.onerror=()=>toast('No pude escuchar bien');r.start()}
function init(){renderChips();renderGrid();counts();renderBag();msg('r','Hola ✦ Soy ROD. Puedo ayudarte a explorar, abrir tu bolsa o mostrar tu compra en imágenes.');try{if(localStorage.getItem('velora_age')==='ok'){$('#age').classList.add('hidden');$('#app').classList.remove('hidden')}}catch(e){}loadShared();
$('#ageOk').onclick=()=>{try{localStorage.setItem('velora_age','ok')}catch(e){}$('#age').classList.add('hidden');$('#app').classList.remove('hidden')};$('#bagHeader').onclick=openBag;$('#dockBag').onclick=openBag;$('#rodOrb').onclick=()=>rodOpen();$('#dockRod').onclick=()=>rodOpen();$('#heroRod').onclick=()=>rodOpen();$('#rodClose').onclick=()=>$('#rod').classList.remove('open');$('#rodSend').onclick=()=>{const v=$('#rodInput').value;$('#rodInput').value='';ask(v)};$('#rodInput').onkeydown=e=>{if(e.key==='Enter')$('#rodSend').click()};$('#voice').onclick=voice;$$('.quick button').forEach(b=>b.onclick=()=>ask(b.dataset.q));$('#search').oninput=e=>{S.q=e.target.value;renderGrid()};$('#sort').onchange=e=>{S.sort=e.target.value;renderGrid()};$('#random').onclick=()=>detail(P[Math.floor(Math.random()*P.length)].id);$('#demoVisual').onclick=()=>{if(!count()){S.cart={'luna-mini':1,'duo-loop':1,'silk-water':1};save();counts();renderBag()}openVisual('bag')};$('#overlay').onclick=closeAll;$('#shareBtn').onclick=share;$('#copyBtn').onclick=()=>S.reservation&&copy(S.reservation.link,'Link copiado');$('#codeBtn').onclick=()=>S.reservation&&copy(S.reservation.code,'Código copiado');$('#shareVisualBtn').onclick=()=>openVisual('reservation',S.reservation.items,S.reservation.code);$('#visualPrev').onclick=()=>moveVisual(-1);$('#visualNext').onclick=()=>moveVisual(1);$('#visualBackQr').onclick=visualToQr;$('#visualShare').onclick=share;$('#visualCloseBtn').onclick=()=>{close('visualModal');openBag()};$('#sharedUse').onclick=useShared;$('#sharedVisual').onclick=()=>S.shared&&openVisual('shared',S.shared.items,S.shared.code||'BOLSA COMPARTIDA');
let sx=0;$('#visualStage').addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});$('#visualStage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)moveVisual(dx<0?1:-1)},{passive:true});
document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c){close(c.dataset.close);return}const a=e.target.closest('[data-add]');if(a){add(a.dataset.add);return}const f=e.target.closest('[data-fav]');if(f){fav(f.dataset.fav);return}const d=e.target.closest('[data-detail]');if(d){detail(d.dataset.detail);return}const ca=e.target.closest('[data-cat]');if(ca){S.cat=ca.dataset.cat;renderChips();renderGrid();return}const q=e.target.closest('[data-qty]');if(q){qty(q.dataset.qty,Number(q.dataset.n));return}const da=e.target.closest('[data-detailadd]');if(da){add(da.dataset.detailadd);close('detailModal');return}const vt=e.target.closest('[data-visual]');if(vt){S.visualIndex=Number(vt.dataset.visual);renderVisual();return}if(e.target.id==='prepare')reservation();if(e.target.id==='bagVisualBtn')openVisual('bag');if(e.target.id==='bagShareQuick')share()});
window.addEventListener('hashchange',loadShared)}
document.addEventListener('DOMContentLoaded',init);
})();