(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const products=()=>window.P||[];
function loadPatch(){if($('#luxuryPatch'))return;const s=document.createElement('style');s.id='luxuryPatch';s.textContent=`.mobileMenuLuxury{display:none;position:fixed;z-index:58;top:98px;left:10px;right:10px;padding:10px;background:rgba(12,11,15,.98);border:1px solid rgba(255,255,255,.08);box-shadow:0 24px 60px rgba(0,0,0,.35);transform:translateY(-12px);opacity:0;pointer-events:none;transition:.2s}.mobileMenuLuxury a{display:block;padding:14px 12px;border-bottom:1px solid rgba(255,255,255,.06);font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#c0b6c0}.mobileMenuLuxury a:last-child{border-bottom:0}.mobileMenuLuxury.open{transform:none;opacity:1;pointer-events:auto}.mobileSwipeHint{display:none}.productionStatus{margin-top:22px;display:flex;align-items:center;gap:8px;color:#837984;font-size:9px;letter-spacing:.05em}.productionStatus i{width:7px;height:7px;border-radius:50%;background:#a9c9b3;box-shadow:0 0 0 5px rgba(169,201,179,.07)}.serviceProofHead{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:30px}.serviceProofHead h2{font:600 clamp(38px,4vw,60px)/1 Manrope;margin:8px 0 0;letter-spacing:-.04em}.serviceProofHead p{max-width:430px;color:#968c97;font-size:11px;line-height:1.7}.serviceProofGrid{display:grid}.serviceCard{padding:25px}.serviceIcon{width:42px;height:42px;display:grid;place-items:center;color:#9d919e;font:700 10px Manrope;margin-bottom:26px}.serviceCard h3{margin:0 0 9px}.footerGrid .mark{border-radius:50%}.menuBtn{display:none}.ageCard{border-radius:6px;background:rgba(13,11,15,.92);max-width:520px}.agePill{background:transparent;border:1px solid rgba(255,255,255,.1);color:#a99daa}.ageCard h1{font-weight:600}.ageCard .primary{border-radius:999px;background:#eee7e1;color:#171318;box-shadow:none}@media(max-width:760px){.menuBtn{display:grid;place-items:center}.mobileMenuLuxury{display:block;top:98px}.mobileSwipeHint{display:flex;align-items:center;justify-content:space-between;margin:10px 0 8px;color:#776d78;font-size:9px;letter-spacing:.08em;text-transform:uppercase}.mobileSwipeHint i{font-style:normal;font-size:16px}.serviceProofHead{display:block}.serviceProofHead p{margin-top:13px}.productionStatus{margin-top:18px}.heroEditorial .heroFrame img{padding:12px}.editorialMedia img{padding:26px}.footerBottom span{display:block}.rodHead{border-radius:0}.grid .card:last-child{margin-right:3px}}@media(min-width:761px){.mobileMenuLuxury{display:none!important}}`;document.head.appendChild(s)}
function product(id){return products().find(p=>p.id===id)}
function setEditorialMedia(){$$('[data-product-media]').forEach(host=>{const p=product(host.dataset.productMedia);if(!p||!p.image)return;let img=host.querySelector('img');if(!img){img=document.createElement('img');host.appendChild(img)}if(img.src!==p.image){img.src=p.image;img.alt=p.name;img.loading='lazy';img.referrerPolicy='no-referrer'}})}
function jumpCategory(cat){location.hash='#catalogo';setTimeout(()=>{const b=$$('[data-cat]').find(x=>x.dataset.cat===cat);if(b)b.click()},90)}
function categoryLinks(){$$('[data-shopcat]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();jumpCategory(el.dataset.shopcat)}))}
function faq(){$$('.faqQ').forEach(q=>q.addEventListener('click',()=>{const item=q.closest('.faqItem');$$('.faqItem.open').filter(x=>x!==item).forEach(x=>x.classList.remove('open'));item.classList.toggle('open')}))}
function header(){const h=$('.top');if(!h)return;const sync=()=>h.classList.toggle('scrolled',scrollY>18);sync();addEventListener('scroll',sync,{passive:true})}
function mobileMenu(){const btn=$('#menuBtn'),menu=$('#mobileMenu');if(!btn||!menu)return;btn.addEventListener('click',()=>menu.classList.toggle('open'));menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));document.addEventListener('click',e=>{if(!menu.contains(e.target)&&!btn.contains(e.target))menu.classList.remove('open')})}
function reveal(){const targets=$$('.luxSection,.editorialBand,.conciergeCard,.serviceProof,.privacy,.faqWrap');targets.forEach(x=>x.classList.add('reveal'));if(!('IntersectionObserver'in window)){targets.forEach(x=>x.classList.add('in'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});targets.forEach(x=>io.observe(x))}
function polishDynamicCopy(){let queued=false;const clean=()=>{$$('.bagFoot .total span').forEach(x=>{if(/referencial/i.test(x.textContent))x.textContent='Total'});$$('.bagFoot p').forEach(x=>{const t='Pago al recoger. Tu selección queda asociada al código generado.';if(x.textContent!==t)x.textContent=t});$$('.priceDemo,.realCatalogNote').forEach(x=>x.remove());queued=false};clean();const mo=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(clean)});mo.observe(document.body,{subtree:true,childList:true})}
function rodCtas(){$$('[data-open-rod]').forEach(b=>b.addEventListener('click',()=>{$('#heroRod')?.click()}))}
function catalogHints(){const grid=$('#grid');if(!grid||$('.mobileSwipeHint'))return;const hint=document.createElement('div');hint.className='mobileSwipeHint';hint.innerHTML='<span>Desliza para explorar</span><i>→</i>';grid.parentElement.insertBefore(hint,grid)}
function accessibility(){$$('.catTile,.moodCard').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}})})}
function init(){loadPatch();setEditorialMedia();categoryLinks();faq();header();mobileMenu();reveal();polishDynamicCopy();rodCtas();catalogHints();accessibility();setTimeout(setEditorialMedia,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();