window.P=[
{id:'luna-mini',name:'LELO SONA 2',brand:'LELO',cat:'Vibradores',price:469.90,badge:'Premium',symbol:'✦',tone:'purple',color:'Morado / Rose Gold',feature:'12 modos · tecnología SenSonic',meta:'Silicona corporal · USB · sumergible',desc:'Masajeador sónico compacto con 12 ajustes, silicona extrasuave y diseño 100% sumergible.',image:'https://cdn.shopify.com/s/files/1/0583/1347/4224/products/lelo-sona-2-cruise-clitoral-stimulator-rechargeable-347825.jpg?format=webp&height=1000&quality=80&v=1715566522&width=1000',sourceUrl:'https://www.lelo.com/es/sona-2',priceLabel:'Precio referencial demo'},
{id:'nova-wand',name:'We-Vibe Tango X',brand:'We-Vibe',cat:'Vibradores',price:319.90,badge:'Compacto',symbol:'↯',tone:'blue',color:'Midnight Blue',feature:'7 modos · 8 intensidades',meta:'IPX7 · recargable · hasta 2 h',desc:'Vibrador bullet compacto, silencioso y resistente al agua, con bloqueo de viaje y carga magnética.',image:'https://www.we-vibe.com/media/catalog/we-vibe/WVI_TangoX_PDP_intheBox_01.jpg',sourceUrl:'https://www.we-vibe.com/us/tango-x',priceLabel:'Precio referencial demo'},
{id:'air-touch',name:'Womanizer Premium 2',brand:'Womanizer',cat:'Vibradores',price:699.90,badge:'Alta gama',symbol:'◉',tone:'blue',color:'Blueberry',feature:'Pleasure Air · Autopilot 2.0',meta:'IPX7 · hasta 240 min · 2 cabezales',desc:'Estimulador premium con tecnología Pleasure Air, función Autopilot y Smart Silence.',image:'https://www.womanizer.com/media/catalog/we-vibe/WMZ_Premium2_Packshots.Flatlay-Blueberry_666x569.jpg',sourceUrl:'https://www.womanizer.com/us/premium-2',priceLabel:'Precio referencial demo'},
{id:'duo-loop',name:'We-Vibe Chorus',brand:'We-Vibe',cat:'Pareja',price:599.90,badge:'Pareja',symbol:'∞',tone:'pink',color:'Cosmic',feature:'Ajustable · control remoto',meta:'App We-Vibe · recargable',desc:'Vibrador ajustable para pareja con control remoto y modos adicionales mediante la app We-Vibe.',image:'https://cdn000.hawttt.com/file/hawttt-img-044/120/2e2c7db9a93d9a2e5eb031cd6e1d5b7042cd259e-84825163-600h.jpg',sourceUrl:'https://www.we-vibe.com/us/chorus',priceLabel:'Precio referencial demo'},
{id:'sync-mini',name:'LELO SORAYA 2',brand:'LELO',cat:'Pareja',price:799.90,badge:'Dual',symbol:'≈',tone:'mint',color:'Deep Rose / Gold',feature:'Doble estimulación · 12 modos',meta:'Silicona extrasuave · sumergible',desc:'Vibrador de doble estimulación con brazo externo flexible, 12 modos y acabado de silicona premium.',image:'https://assets.lelo.com/dx/2022-03/Hero_block_desktop_1920x840px_SORAYA_2.webp?VersionId=ofKwUL7uGWPO2CuHvSb6cc11Js.AbzJc',sourceUrl:'https://www.lelo.com/es/soraya-2',priceLabel:'Precio referencial demo'},
{id:'silk-water',name:'Durex Play Feel 50 ml',brand:'Durex',cat:'Lubricantes',price:39.90,badge:'Base agua',symbol:'◌',tone:'blue',color:'Transparente',feature:'Textura ligera · base agua',meta:'Botella 50 ml',desc:'Lubricante de base acuosa en formato compacto de 50 ml, apto para usar con preservativos y juguetes compatibles.',image:'https://www.chemist-4-u.com/media/catalog/product/cache/f82c79c06fdfbb9bff4567c21265baf6/d/u/durexplayfeel_1_.png',sourceUrl:'https://www.chemist-4-u.com/durex-play-feel-lubricant-50ml',priceLabel:'Precio referencial demo'},
{id:'safe-ultra',name:'SKYN Elite',brand:'SKYN',cat:'Preservativos',price:59.90,badge:'Ultra fino',symbol:'◇',tone:'black',color:'Negro / Dorado',feature:'Sin látex · poliisopreno',meta:'Presentación demo',desc:'Preservativos SKYN Elite fabricados con poliisopreno sintético, diseñados para una sensación ultrafina.',image:'https://m.media-amazon.com/images/I/71QEE0A+dCL._AC_SX679_.jpg',sourceUrl:'https://skynfeel.com/',priceLabel:'Precio referencial demo'},
{id:'safe-classic',name:'Durex Invisible 003',brand:'Durex',cat:'Preservativos',price:44.90,badge:'Pack x10',symbol:'◇',tone:'red',color:'Rojo / Blanco',feature:'Ultrafino · prelubricado',meta:'Pack de 10 · látex natural',desc:'Pack de preservativos Durex Invisible 003 ultrafinos y prelubricados.',image:'https://m.media-amazon.com/images/I/61+1eLPvSgL.jpg',sourceUrl:'https://www.durex.com/',priceLabel:'Precio referencial demo'}
];